CPPFLAGS	+= 
CFLAGS		+=

SRC		:= \
		message.c \
		mp_channel.c \
		tpool.c \
		grp_channel.c \
		rts_init.c \
		sync.c \

MODULE		:= $(RTS)/communication/panda

include $(RTS)/include/make/module.mk
