# (c) copyright 1995 by the Vrije Universiteit, Amsterdam, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Orca distribution.

# $Id: Makefile,v 1.2 1995/07/31 09:15:50 ceriel Exp $

# global flags for the C compiler
NAMELIST	= Y

# include rts- and architecture-specific options
include system.mk
