CPPFLAGS	+=
CFLAGS		+=

SRC		:= \
		collection.c \
		forest.c \
		message_handlers.c \
		reduction_function.c \
		timeout.c \
		coll_channel.c \
		coll_operation.c \
		

MODULE		:= $(RTS)/collection

include $(RTS)/include/make/module.mk
