PANDA           := /usr/proj/panda/panda2.0/latest_greatest
ARCH            := amoeba_tim

# Additional local flags
CPPFLAGS        += -UCHECK
CFLAGS          += -O2 -g -ansi -Wall -pedantic -Wstrict-prototypes \
		   -Wmissing-prototypes
LDFLAGS         +=


include $(PANDA)/tst/src/bg2/Makefile
