# $Id: Makefile,v 1.1 1995/06/19 11:14:47 ceriel Exp $

# global flags for the C compiler
NAMELIST	= Y

# global flags for the C preprocessor
SPEC_DEFINES	= -DACCOUNTING

# include rts- and architecture-specific stuff
include system.mk
