# (c) copyright 1995 by the Vrije Universiteit, Amsterdam, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Orca distribution.

# $Id: Makefile,v 1.3 1996/10/09 14:39:44 ceriel Exp $

# global flags for the C compiler
OPTIM		= Y
NAMELIST	= Y

# global flags for the C preprocessor
SPEC_DEFINES	= -DACCOUNTING -DTRACING

# special version: tracing
SPECIAL		= tracing
BACK		= ../

# include rts- and architecture-specific options
include ../system.mk
