CPPFLAGS	+= 
CFLAGS		+=

SRC		:= \
		consistency.c \
		instance.c \
		partition.c \
		pdg.c \
		po.c \
		po_invocation.c \
		po_marshall.c \
		gather_marshall.c \
		po_rts_object.c \


MODULE		:= $(RTS)/po

include $(RTS)/include/make/module.mk
