CC=cc
CFLAGS=-I. -DNDEBUG -O

OFILES=	LLlex.o \
	LLmessage.o \
	ch3bin.o \
	ch3mon.o \
	domacro.o \
	error.o \
	idf.o \
	init.o \
	input.o \
	main.o \
	options.o \
	preprocess.o \
	replace.o \
	skip.o \
	tokenname.o \
	next.o \
	expr.o \
	tokenfile.o \
	expression.o \
	Lpars.o \
	char.o \
	symbol2str.o \
	Malloc.o \
	Realloc.o \
	Salloc.o \
	close.o \
	doprnt.o \
	fprint.o \
	long2str.o \
	open.o \
	read.o \
	sprint.o \
	st_alloc.o \
	stop.o \
	strrindex.o \
	system.o \
	time.o \
	write.o \
	format.o

ncpp: $(OFILES)
	$(CC) $(LDFLAGS) -o ncpp $(OFILES)

LLlex.o:
LLmessage.o:
ch3bin.o:
ch3mon.o:
domacro.o:
error.o:
idf.o:
init.o:
input.o:
main.o:
options.o:
preprocess.o:
replace.o:
skip.o:
tokenname.o:
next.o:
expr.o:
tokenfile.o:
expression.o:
Lpars.o:
char.o:
symbol2str.o:
Malloc.o:
Realloc.o:
Salloc.o:
close.o:
doprnt.o:
fprint.o:
long2str.o:
open.o:
read.o:
sprint.o:
st_alloc.o:
stop.o:
strrindex.o:
system.o:
time.o:
write.o:
format.o:
