# (c) copyright 1995 by the Vrije Universiteit, Amsterdam, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Orca distribution.

# $Id: Makefile,v 1.3 1996/10/09 14:40:01 ceriel Exp $

# global flags for the C compiler
OPTIM		= Y
EXTRAOPTIM	= Y

# global flags for the C preprocessor
SPEC_DEFINES	= -DNDEBUG

# special version: optimized
SPECIAL		= optimized
BACK		= ../

# include rts- and architecture-specific options
include ../system.mk
