	.global	_pan_small_handler_0
	.global	_PAN_0
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_0:
	ba _pan_small_enqueue
	mov 0,%o4

#ifndef CMOST
	.size	_pan_small_handler_0,.-_pan_small_handler_0
#endif
_PAN_0:				



	.global	_pan_small_handler_1
	.global	_PAN_1
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_1:
	ba _pan_small_enqueue
	mov 1,%o4

#ifndef CMOST
	.size	_pan_small_handler_1,.-_pan_small_handler_1
#endif
_PAN_1:				



	.global	_pan_small_handler_2
	.global	_PAN_2
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_2:
	ba _pan_small_enqueue
	mov 2,%o4

#ifndef CMOST
	.size	_pan_small_handler_2,.-_pan_small_handler_2
#endif
_PAN_2:				



	.global	_pan_small_handler_3
	.global	_PAN_3
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_3:
	ba _pan_small_enqueue
	mov 3,%o4

#ifndef CMOST
	.size	_pan_small_handler_3,.-_pan_small_handler_3
#endif
_PAN_3:				



	.global	_pan_small_handler_4
	.global	_PAN_4
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_4:
	ba _pan_small_enqueue
	mov 4,%o4

#ifndef CMOST
	.size	_pan_small_handler_4,.-_pan_small_handler_4
#endif
_PAN_4:				



	.global	_pan_small_handler_5
	.global	_PAN_5
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_5:
	ba _pan_small_enqueue
	mov 5,%o4

#ifndef CMOST
	.size	_pan_small_handler_5,.-_pan_small_handler_5
#endif
_PAN_5:				



	.global	_pan_small_handler_6
	.global	_PAN_6
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_6:
	ba _pan_small_enqueue
	mov 6,%o4

#ifndef CMOST
	.size	_pan_small_handler_6,.-_pan_small_handler_6
#endif
_PAN_6:				



	.global	_pan_small_handler_7
	.global	_PAN_7
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_7:
	ba _pan_small_enqueue
	mov 7,%o4

#ifndef CMOST
	.size	_pan_small_handler_7,.-_pan_small_handler_7
#endif
_PAN_7:				



	.global	_pan_small_handler_8
	.global	_PAN_8
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_8:
	ba _pan_small_enqueue
	mov 8,%o4

#ifndef CMOST
	.size	_pan_small_handler_8,.-_pan_small_handler_8
#endif
_PAN_8:				



	.global	_pan_small_handler_9
	.global	_PAN_9
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_9:
	ba _pan_small_enqueue
	mov 9,%o4

#ifndef CMOST
	.size	_pan_small_handler_9,.-_pan_small_handler_9
#endif
_PAN_9:				



	.global	_pan_small_handler_10
	.global	_PAN_10
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_10:
	ba _pan_small_enqueue
	mov 10,%o4

#ifndef CMOST
	.size	_pan_small_handler_10,.-_pan_small_handler_10
#endif
_PAN_10:				



	.global	_pan_small_handler_11
	.global	_PAN_11
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_11:
	ba _pan_small_enqueue
	mov 11,%o4

#ifndef CMOST
	.size	_pan_small_handler_11,.-_pan_small_handler_11
#endif
_PAN_11:				



	.global	_pan_small_handler_12
	.global	_PAN_12
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_12:
	ba _pan_small_enqueue
	mov 12,%o4

#ifndef CMOST
	.size	_pan_small_handler_12,.-_pan_small_handler_12
#endif
_PAN_12:				



	.global	_pan_small_handler_13
	.global	_PAN_13
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_13:
	ba _pan_small_enqueue
	mov 13,%o4

#ifndef CMOST
	.size	_pan_small_handler_13,.-_pan_small_handler_13
#endif
_PAN_13:				



	.global	_pan_small_handler_14
	.global	_PAN_14
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_14:
	ba _pan_small_enqueue
	mov 14,%o4

#ifndef CMOST
	.size	_pan_small_handler_14,.-_pan_small_handler_14
#endif
_PAN_14:				



	.global	_pan_small_handler_15
	.global	_PAN_15
	.global	_pan_small_enqueue
	.align	4
_pan_small_handler_15:
	ba _pan_small_enqueue
	mov 15,%o4

#ifndef CMOST
	.size	_pan_small_handler_15,.-_pan_small_handler_15
#endif
_PAN_15:				



