# (c) copyright 1995 by the Vrije Universiteit, Amsterdam, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Panda distribution.

CPPFLAGS	+= $(GROUP_CPPFLAGS)
CFLAGS		+= $(GROUP_CFLAGS)

SRC		:= \
		grp_global.c \
		grp_group.c \
		grp_header.c \
		grp_send_rcve.c \
		grp_stats.c \
		grp_sweep.c \
		grp_ns.c

MODULE		:= $(PANDA)/src/group

include $(PANDA)/include/module.mk
