# (c) copyright 1995 by the Vrije Universiteit, Amsterdam, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Orca distribution.

# $Id: Makefile,v 1.1 1997/01/06 14:18:18 ceriel Exp $

# global flags for the C compiler
OPTIM		= Y
PROFILING	= Y
NAMELIST	= Y

# global flags for the C preprocessor
SPEC_DEFINES	= -DACCOUNTING

# special version: profiling
SPECIAL		= profiling
BACK		= ../

# include rts- and architecture-specific options
include ../system.mk
