# (c) copyright 1995 by the Vrije Universiteit, Amsterdam, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Orca distribution.

all:
	( cd system; make )
	( cd alloc; make )
	( cd flt_arith; make )

clean:
	( cd system; make clean )
	( cd alloc; make clean )
	( cd flt_arith; make clean )
