# (c) copyright 1995 by the Vrije Universiteit, Amsterdam, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Orca distribution.

# $Id: Makefile,v 1.1 1998/06/11 12:10:07 ceriel Exp $

# global flags for the C compiler
NAMELIST	= Y

# global flags for the C preprocessor
SPEC_DEFINES	= -DACCOUNTING

# include rts- and architecture-specific stuff
include system.mk
