# $Id: Makefile,v 1.2 1996/10/09 14:39:33 ceriel Exp $

# global flags for the C compiler
OPTIM		= Y
NAMELIST	= Y

# global flags for the C preprocessor
SPEC_DEFINES	= -DACCOUNTING -DTRACING

# special version: tracing
SPECIAL		= tracing
BACK		= ../

# include rts- and architecture-specific options
include ../system.mk
