# (c) copyright 1995 by the Vrije Universiteit, Amsterdam, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Panda distribution.

# Add local flags
CPPFLAGS	+= $(UTIL_CPPFLAGS)
CFLAGS		+= $(UTIL_CFLAGS)

SRC		:= \
		pan_error.c \
		pan_malloc.c

MODULE		:= $(PANDA)/src/system/bare_bones
GENERIC		:= $(PANDA)/src/system/generic

include $(PANDA)/include/module.mk
