# $Id: Makefile,v 1.2 1996/10/09 14:39:30 ceriel Exp $

# global flags for the C compiler
OPTIM		= Y
PROFILING	= Y
NAMELIST	= Y

# global flags for the C preprocessor
SPEC_DEFINES	= -DACCOUNTING

# special version: profiling
SPECIAL		= profiling
BACK		= ../

# include rts- and architecture-specific options
include ../system.mk
