# (c) copyright 1995 by the Vrije Universiteit, Amsterdam, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Orca distribution.

distr:
	echo 'char *Version = "Orca-to-C compiler, main branch, date: XXX";' | \
		sed "s/XXX/`date`/" > Version.c
