#!/bin/sh
# (c) copyright 1995 by the Vrije Universiteit, Amsterdam, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Orca distribution.

# $Id: makedepend,v 1.3 1996/10/30 13:26:47 ceriel Exp $

# script for producing dependencies with gcc, called as the X11 makedepend.

FILE=Makefile

trap 'rm -f /tmp/tmp$$' 0 1 2 3 15

for i
do
	case $i in
	--)	;;
	-f*)	FILE=`expr "$i" : '-f\(.*\)'`
		;;
	-*) 	ARGS="$ARGS '$i'"
		;;
	*)	FILES="$FILES $i"
		;;
	esac
done
cp $FILE /tmp/tmp$$
ed - /tmp/tmp$$ << 'EOF'
/^# DO NOT DELETE THIS LINE -- make depend depends on it./,$d
w
q
EOF
echo '# DO NOT DELETE THIS LINE -- make depend depends on it.' >> /tmp/tmp$$
eval gcc -M $ARGS $FILES | sed 's/o :/o:/' >> /tmp/tmp$$
cp $FILE $FILE.bak
cp /tmp/tmp$$ $FILE
