.\"
.\" (c) copyright 1995 by the Vrije Universiteit, Amsterdam, The Netherlands.
.\" For full copyright and restrictions on use see the file COPYRIGHT in the
.\" top level of the Orca distribution.
.\"
.\" $Id: oc_panda.1,v 1.8 1998/10/27 15:23:41 ceriel Exp $
.TH OC_PANDA 1
.ad
.SH NAME
oc_panda \- Orca with the Panda runtime system
.SH SYNOPSIS
.B oc_panda
.RI [ option ] 
.I sources
.SH DESCRIPTION
This command compiles an Orca program for the Panda runtime system.
In addition to the usual
.IR oc (1)
options, the
.IR panc (1)
options for selecting the proper version of Panda are also available.
.LP
This command is just a simple front-end for
.IR oc (1).
.SH "SEE ALSO"
oc(1)
panc(1)
.SH "REMARKS"
Some of the combinations described here may not be available in the
current installation. Other options may exist at one time or another.
