# (c) copyright 1995 by the Vrije Universiteit, Amsterdam, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Orca distribution.

# $Id: Makefile,v 1.2 1998/09/02 16:25:44 ceriel Exp $

# global flags for the C compiler
OPTIM		= Y
EXTRAOPTIM	= Y
NAMELIST	= Y

# global flags for the C preprocessor
SPEC_DEFINES	= -UACCOUNTING -DNDEBUG -DINLINE_FUNCTIONS -DNSTATISTICS

# special version: optimized
SPECIAL		= optimized
BACK		= ../

# include rts- and architecture-specific options
include ../system.mk
