CPPFLAGS	+= $(GROUP_CPPFLAGS)
CFLAGS		+= $(GROUP_CFLAGS)

SRC		:= \
		global.c \
		group_tab.c \
		grp.c \
		grp_ns.c \
		grp_stats.c \
		header.c \
		join_leave.c \
		name.c

MODULE		:= $(PANDA)/src/group/ord_msg

include $(PANDA)/include/module.mk
