# $Id: Makefile,v 1.2 1996/10/09 14:39:52 ceriel Exp $

# global flags for the C compiler
OPTIM		= Y
EXTRAOPTIM	= Y

# global flags for the C preprocessor
SPEC_DEFINES	= -DNDEBUG

# special version: optimized
SPECIAL		= optimized
BACK		= ../

# include rts- and architecture-specific options
include ../system.mk
