CFLAGS=-O -I/usr/openwin/include

all:		DrawArea.o xdisplay.o

DrawArea.o:	DrawArea.h DrawAreaP.h orca_link.h std_colors.h xdisplay.h
xdisplay.o:	DrawArea.h DrawAreaP.h orca_link.h std_colors.h xdisplay.h
